In [1]:
import numpy as np
from scipy import stats

In [2]:
# load data
path = "data/graphs/"

edges1 = np.genfromtxt(path+"anthrocon_edgelist.csv", dtype=int, delimiter=',')
edges2 = np.genfromtxt(path+"comiccon2017_edgelist.csv", dtype=int, delimiter=',')
edges3 = np.genfromtxt(path+"icann2016_edgelist.csv", dtype=int, delimiter=',')

In [3]:
display(edges1)
display(edges2)
display(edges3)

array([[ 542,   29],
       [ 542,   87],
       [ 542,  836],
       ...,
       [ 151, 1003],
       [ 761,  564],
       [ 761, 1003]])

array([[ 745, 1511],
       [ 316, 1930],
       [  70,   77],
       ...,
       [1890, 1477],
       [1890, 1459],
       [1890, 1791]])

array([[552, 394],
       [552, 305],
       [552, 916],
       ...,
       [261, 378],
       [261,  18],
       [261, 241]])

In [4]:
display(stats.describe(edges1))
display(stats.describe(edges2))
display(stats.describe(edges3))

DescribeResult(nobs=15788, minmax=(array([1, 0]), array([1056, 1059])), mean=array([523.05776539, 543.65600456]), variance=array([77276.49758143, 91135.41475649]), skewness=array([0.0745417 , 0.01764497]), kurtosis=array([-0.94816993, -1.18612342]))

DescribeResult(nobs=8203, minmax=(array([0, 0]), array([2493, 2494])), mean=array([1238.76679264, 1239.69937828]), variance=array([499563.34563208, 517456.19808178]), skewness=array([0.00912743, 0.0083117 ]), kurtosis=array([-1.15662223, -1.17622111]))

DescribeResult(nobs=17045, minmax=(array([0, 0]), array([1015, 1015])), mean=array([516.46817248, 507.649868  ]), variance=array([82645.83689179, 86726.58333796]), skewness=array([-0.086726  , -0.01514735]), kurtosis=array([-1.14439861, -1.19235445]))

In [5]:
def adjacency_matrix_from_edges(edges):
    n = np.amax(edges) + 1
    adj_matrix = np.zeros((n, n))
    
    for [A, B] in edges:
        adj_matrix[A][B] += 1
    
    return adj_matrix

In [6]:
adj_matrix1 = adjacency_matrix_from_edges(edges1)
adj_matrix2 = adjacency_matrix_from_edges(edges2)
adj_matrix3 = adjacency_matrix_from_edges(edges3)