In [41]:
import numpy as np
import os
import utils.graph_utils as graph_utils
import utils.IO_utils as io_utils
import utils.plot_utils as plot_utils
import importlib
import matplotlib.pyplot as plt
import joblib
from sklearn import metrics

In [42]:
# reload module
importlib.reload(graph_utils)
importlib.reload(io_utils)
importlib.reload(plot_utils)

<module 'utils.plot_utils' from '/Users/anton/local/repos/asds/results/utils/plot_utils.py'>

In [56]:
#input_file = "anthrocon"
#input_file = "comiccon2017"
input_file = "icann2016"

In [57]:
# load graph
G = graph_utils.load_csv_edges(os.path.join('./data', input_file, 'twitter' + '.csv'), undirected=True)


In [58]:
# load labels_true
labels_true, k = io_utils.load_ground_true(file_name=input_file+"/twitter")
labels_true = np.array(labels_true)

display(labels_true)

array([1, 0, 1, ..., 0, 1, 0])

In [59]:
# load labels_pred
labels_pred = np.loadtxt('./data/'+input_file+'/labels_pred.txt').astype(int)

In [61]:
# load embeddings
# path needs to be changed for input_file
node_embedding = io_utils.load_embedding(input_file+"/twitter_alpha-0.1_beta-5_ws-10_neg-5_lr-0.025_icom-64_ind-64_k-2_ds-0.0")

display(node_embedding)

array([[ 0.0619565 ,  1.12690997],
       [-0.0644869 ,  1.03811002],
       [-0.201978  ,  0.98284   ],
       ..., 
       [-3.89945006,  3.59325004],
       [ 0.1753    ,  1.14503002],
       [-0.0585161 ,  1.07018995]], dtype=float32)

In [62]:
# plot graph

#plot_utils.graph_plot(G, "graph")

In [63]:
# plot node space 2D

plot_utils.node_space_plot_2D(node_embedding, labels_pred)

In [64]:
# load g_mixture
g_mixture = joblib.load('./data/'+input_file+'/g_mixture.joblib') 

In [65]:
print("labels_true: ", labels_true)
print("labels_pred: ", labels_pred)

labels_true:  [1 0 1 ..., 0 1 0]
labels_pred:  [1 1 1 ..., 0 1 1]


In [66]:
print("labels_true:")
display(np.histogram(labels_true))

print("labels_pred:")
display(np.histogram(labels_pred))

labels_true:


(array([706,   0,   0,   0,   0,   0,   0,   0,   0, 310]),
 array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ]))

labels_pred:


(array([159,   0,   0,   0,   0,   0,   0,   0,   0, 857]),
 array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ]))

In [69]:
# NMI

metrics.normalized_mutual_info_score(labels_true, labels_pred)

0.0031368490563390529