In [1]:
import numpy as np
import os
import utils.graph_utils as graph_utils
import utils.IO_utils as io_utils
import utils.plot_utils as plot_utils
import importlib
import matplotlib.pyplot as plt
import joblib
from sklearn import metrics

In [2]:
# reload module
importlib.reload(graph_utils)
importlib.reload(io_utils)
importlib.reload(plot_utils)

<module 'utils.plot_utils' from '/Users/anton/local/repos/asds/results/utils/plot_utils.py'>

In [6]:
input_file = "anthrocon"
#input_file = "comiccon2017"
#input_file = "icann2016"

In [7]:
# load graph
G = graph_utils.load_csv_edges(os.path.join('./data', input_file, 'twitter' + '.csv'), undirected=True)


In [10]:
# load labels_true
labels_true, k = io_utils.load_ground_true(file_name=input_file+"/twitter")
labels_true = np.array(labels_true)

display(labels_true)

array([0, 1, 0, ..., 1, 0, 0])

In [12]:
# load labels_pred
labels_pred = np.loadtxt('./data/'+input_file+'/labels_pred.txt').astype(int)

In [17]:
# load embeddings
node_embedding = io_utils.load_embedding(input_file+"/twitter_alpha-0.1_beta-5_ws-10_neg-5_lr-0.025_icom-62_ind-62_k-2_ds-0.0")

display(node_embedding)

array([[-0.19118799, -1.12738001],
       [ 0.38234001, -0.79779202],
       [-0.00678613, -1.03595996],
       ..., 
       [ 0.774526  , -0.82578701],
       [ 0.0311986 , -1.03365004],
       [-0.50114   , -1.25586998]], dtype=float32)

In [19]:
# plot graph

#plot_utils.graph_plot(G, "graph")

In [20]:
# plot node space 2D

plot_utils.node_space_plot_2D(node_embedding, labels_pred)

In [23]:
# load g_mixture
g_mixture = joblib.load('./data/'+input_file+'/g_mixture.joblib') 

In [24]:
print("labels_true: ", labels_true)
print("labels_pred: ", labels_pred)

labels_true:  [0 1 0 ..., 1 0 0]
labels_pred:  [0 1 0 ..., 0 0 0]


In [25]:
print("labels_true:")
display(np.histogram(labels_true))

print("labels_pred:")
display(np.histogram(labels_pred))

labels_true:


(array([709,   0,   0,   0,   0,   0,   0,   0,   0, 351]),
 array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ]))

labels_pred:


(array([911,   0,   0,   0,   0,   0,   0,   0,   0, 149]),
 array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ]))

In [27]:
# NMI

metrics.normalized_mutual_info_score(labels_true, labels_pred)

0.00070290216313934658