In [104]:
import numpy as np
import os
import utils.graph_utils as graph_utils
import utils.IO_utils as io_utils
import utils.plot_utils as plot_utils
import importlib
import matplotlib.pyplot as plt
import joblib
from sklearn import metrics

In [105]:
# reload module
importlib.reload(graph_utils)
importlib.reload(io_utils)
importlib.reload(plot_utils)

<module 'utils.plot_utils' from '/Users/anton/local/repos/asds/ComE/utils/plot_utils.py'>

In [106]:
input_file = "twitter"

In [107]:
# load graph
G = graph_utils.load_csv_edges(os.path.join('./data', input_file, input_file + '.csv'), undirected=True)

In [108]:
# load labels_true
labels_true, k = io_utils.load_ground_true(file_name="twitter/twitter")
labels_true = np.array(labels_true)

In [109]:
# load embeddings
node_embedding = io_utils.load_embedding("twitter_alpha-0.1_beta-0.1_ws-10_neg-5_lr-0.025_icom-62_ind-62_k-2_ds-0.0")

In [110]:
# load labels_pred
labels_pred = np.loadtxt('./data/labels_pred.txt').astype(int)

In [111]:
# load g_mixture
g_mixture = joblib.load('./data/g_mixture.joblib') 

In [112]:
print("labels_true: ", labels_true)
print("labels_pred: ", labels_pred)

labels_true:  [0 1 0 ..., 1 0 0]
labels_pred:  [1 1 1 ..., 1 1 1]


In [113]:
print("labels_true:")
display(np.histogram(labels_true))

print("labels_pred:")
display(np.histogram(labels_pred))

labels_true:


(array([709,   0,   0,   0,   0,   0,   0,   0,   0, 351]),
 array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ]))

labels_pred:


(array([  27,    0,    0,    0,    0,    0,    0,    0,    0, 1033]),
 array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ]))

In [115]:
# NMI

metrics.normalized_mutual_info_score(labels_true, labels_pred)

0.00032511124519870384